"""empty message

Revision ID: 04460142a4ec
Revises: a71424c13187
Create Date: 2016-08-11 18:46:18.522000

"""

# revision identifiers, used by Alembic.
revision = '04460142a4ec'
down_revision = 'a71424c13187'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
